// Tasuku OpenCode Plugin
// Auto-generated by tk hooks install --opencode
// Provides Tasuku integration hooks for OpenCode sessions

export const TasukuPlugin = async ({ project, client, $, directory }) => {
  // Helper to run tk commands
  const tk = async (...args) => {
    try {
      const result = await $`tk ${args.join(' ')}`;
      return result.text();
    } catch (e) {
      return '';
    }
  };

  return {
    // Show context summary when session starts
    'session.created': async (event) => {
      const output = await tk('hooks', 'session');
      if (output.trim()) {
        client.app.log('info', output);
      }
    },

    // Remind about running timers when session goes idle
    'session.idle': async (event) => {
      const output = await tk('hooks', 'stop-reminder');
      if (output.trim()) {
        client.app.log('info', output);
      }
    },

    // Check TodoWrite output for project-level tasks and completed bug fixes
    'todo.updated': async (event) => {
      if (!event.todos || event.todos.length === 0) return;

      // Run todo check for:
      // 1. Completed bug fixes (to prompt for learnings)
      // 2. Project-level tasks that should be persisted
      const hasRelevantItems = event.todos.some(t =>
        t.status === 'completed' || t.status === 'pending' || t.status === 'in_progress'
      );
      if (!hasRelevantItems) return;

      // Run todo check (it reads from environment)
      process.env.TOOL_INPUT = JSON.stringify({ todos: event.todos });
      const output = await tk('hooks', 'todo-check');
      if (output.trim()) {
        client.app.log('info', output);
      }
    },

    // Prompt for insights after significant exploration
    'tool.execute.after': async (event) => {
      // Only trigger for exploration-type tools
      const explorationTools = ['search', 'read', 'glob', 'grep', 'bash'];
      if (!explorationTools.some(t => event.tool?.toLowerCase().includes(t))) {
        return;
      }

      // Don't spam - only prompt occasionally
      // (OpenCode will handle deduplication internally)
    },
  };
};

// Export as default for OpenCode plugin discovery
export default TasukuPlugin;
