package hooks

// OpenCode hooks/plugin configuration.
// OpenCode uses a plugin system with JS/TS files in .opencode/plugin/ or ~/.config/opencode/plugin/
//
// Plugin files export an async function receiving a context object:
//
//	export const TasukuPlugin = async ({ project, client, $, directory, worktree }) => {
//	  return {
//	    'session.created': async (event) => { ... },
//	    'session.idle': async (event) => { ... },
//	    'tool.execute.after': async (event) => { ... },
//	  }
//	}
//
// Available hooks include:
//   - session.created, session.idle, session.status, session.updated, session.deleted
//   - tool.execute.before, tool.execute.after
//   - message.updated, message.removed
//   - file.edited, file.watcher.updated
//   - todo.updated
//   - And more...
//
// The plugin uses Bun's shell API ($) for command execution.

import (
	"fmt"
	"os"
	"path/filepath"
)

const openCodePluginName = "tasuku.js"

// tasukuOpenCodePlugin is the JavaScript plugin source for OpenCode integration
const tasukuOpenCodePlugin = `// Tasuku OpenCode Plugin
// Auto-generated by tk hooks install --opencode
// Provides Tasuku integration hooks for OpenCode sessions

export const TasukuPlugin = async ({ project, client, $, directory }) => {
  // Helper to run tk commands
  const tk = async (...args) => {
    try {
      const result = await $` + "`tk ${args.join(' ')}`" + `;
      return result.text();
    } catch (e) {
      return '';
    }
  };

  return {
    // Show context summary when session starts
    'session.created': async (event) => {
      const output = await tk('hooks', 'session');
      if (output.trim()) {
        client.app.log('info', output);
      }
    },

    // Remind about running timers when session goes idle
    'session.idle': async (event) => {
      const output = await tk('hooks', 'stop-reminder');
      if (output.trim()) {
        client.app.log('info', output);
      }
    },

    // Check TodoWrite output for project-level tasks and completed bug fixes
    'todo.updated': async (event) => {
      if (!event.todos || event.todos.length === 0) return;

      // Run todo check for:
      // 1. Completed bug fixes (to prompt for learnings)
      // 2. Project-level tasks that should be persisted
      const hasRelevantItems = event.todos.some(t =>
        t.status === 'completed' || t.status === 'pending' || t.status === 'in_progress'
      );
      if (!hasRelevantItems) return;

      // Run todo check (it reads from environment)
      process.env.TOOL_INPUT = JSON.stringify({ todos: event.todos });
      const output = await tk('hooks', 'todo-check');
      if (output.trim()) {
        client.app.log('info', output);
      }
    },

    // Prompt for insights after significant exploration
    'tool.execute.after': async (event) => {
      // Only trigger for exploration-type tools
      const explorationTools = ['search', 'read', 'glob', 'grep', 'bash'];
      if (!explorationTools.some(t => event.tool?.toLowerCase().includes(t))) {
        return;
      }

      // Don't spam - only prompt occasionally
      // (OpenCode will handle deduplication internally)
    },
  };
};

// Export as default for OpenCode plugin discovery
export default TasukuPlugin;
`

func getOpenCodePluginPath(local bool) string {
	if local {
		return filepath.Join(".opencode", "plugin", openCodePluginName)
	}

	configDir := os.Getenv("XDG_CONFIG_HOME")
	if configDir == "" {
		home, _ := os.UserHomeDir()
		configDir = filepath.Join(home, ".config")
	}
	return filepath.Join(configDir, "opencode", "plugin", openCodePluginName)
}

func getOpenCodePluginDir(local bool) string {
	return filepath.Dir(getOpenCodePluginPath(local))
}

// installOpenCodeHooks installs Tasuku plugin in OpenCode configuration.
func installOpenCodeHooks(force, local bool) error {
	// Check if OpenCode is detected
	detected := false
	if local {
		// Check for opencode.json or .opencode/ in project
		if _, err := os.Stat("opencode.json"); err == nil {
			detected = true
		}
		if _, err := os.Stat(".opencode"); err == nil {
			detected = true
		}
	} else {
		// Check for global OpenCode config
		configDir := os.Getenv("XDG_CONFIG_HOME")
		if configDir == "" {
			home, _ := os.UserHomeDir()
			configDir = filepath.Join(home, ".config")
		}
		opencodePath := filepath.Join(configDir, "opencode")
		if _, err := os.Stat(opencodePath); err == nil {
			detected = true
		}
	}

	if !detected && !force {
		location := "global"
		if local {
			location = "project"
		}
		fmt.Printf("OpenCode not detected (%s). Use --force to install anyway.\n", location)
		return nil
	}

	pluginPath := getOpenCodePluginPath(local)
	pluginDir := getOpenCodePluginDir(local)

	// Check if plugin already exists
	if _, err := os.Stat(pluginPath); err == nil && !force {
		fmt.Println("Tasuku plugin already installed in OpenCode.")
		fmt.Println("Use --force to reinstall.")
		return nil
	}

	// Create plugin directory
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		return fmt.Errorf("failed to create plugin directory: %w", err)
	}

	// Write plugin file
	if err := os.WriteFile(pluginPath, []byte(tasukuOpenCodePlugin), 0644); err != nil {
		return fmt.Errorf("failed to write plugin: %w", err)
	}

	location := "global"
	if local {
		location = "project"
	}
	fmt.Printf("Tasuku plugin installed in OpenCode (%s):\n", location)
	fmt.Printf("  %s\n", pluginPath)
	fmt.Println()
	fmt.Println("Hooks installed:")
	fmt.Println("  - session.created: Shows context summary at session start")
	fmt.Println("  - session.idle: Reminds about running timers")
	fmt.Println("  - todo.updated: Checks for project-level tasks")
	fmt.Println()
	fmt.Println("Restart OpenCode for plugin to take effect.")

	return nil
}

// uninstallOpenCodeHooks removes Tasuku plugin from OpenCode.
func uninstallOpenCodeHooks(local bool) error {
	pluginPath := getOpenCodePluginPath(local)

	if _, err := os.Stat(pluginPath); os.IsNotExist(err) {
		fmt.Println("No Tasuku plugin found in OpenCode.")
		return nil
	}

	if err := os.Remove(pluginPath); err != nil {
		return fmt.Errorf("failed to remove plugin: %w", err)
	}

	// Try to remove empty plugin directory
	pluginDir := getOpenCodePluginDir(local)
	os.Remove(pluginDir) // Ignore error if not empty

	location := "global"
	if local {
		location = "project"
	}
	fmt.Printf("Tasuku plugin removed from OpenCode (%s).\n", location)

	return nil
}
